server.port=8082

# DATASOURCER
spring.datasource.url=jdbc:postgresql://localhost:5432/ms-stock-control
spring.datasource.username=dev
spring.datasource.password=dev
spring.datasource.driver-class-name=org.postgresql.Driver

#Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate

spring.web.error.include-stacktrace=never
spring.jackson.mapper.sort-properties-alphabetically=false
api.security.token.secret=my-secret

# Actuator
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true