# DATASOURCER
spring.datasource.url=jdbc:postgresql://localhost:5432/ms-stock-control
spring.datasource.username=dev
spring.datasource.password=dev
spring.datasource.driver-class-name=org.postgresql.Driver

#Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate

#Server
server.port=8082

#ERROR
spring.web.error.include-stacktrace=never

spring.jackson.mapper.sort-properties-alphabetically=false

api.security.token.secret="teste