services:
  rabbitmq:
    image: rabbitmq:4.2-management-alpine
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - rabbitmq-log:/var/log/rabbitmq
    networks:
      - rabbitmq-network
volumes:
  rabbitmq-data:
  rabbitmq-log:

networks:
  rabbitmq-network:
    driver: bridge