# DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/ms-user
spring.datasource.username=dev
spring.datasource.password=dev

# JPA / HIBERNATE
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate

# SERVER
server.port=8081
spring.web.error.include-stacktrace=never

# SECRET
api.security.token.secret=${JWT_TOKEN}

# RABBITMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=dev
spring.rabbitmq.password=dev
broker.queue.email.name=default.email
