# SERVER
server.port=8080
spring.web.error.include-stacktrace=never

# RABBITMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=dev
spring.rabbitmq.password=dev
broker.queue.email.name=default.email

# === E-MAIL ===
api.security.resend.token=${RESEND_API_KEY}
api.security.resend.email=${RESEND_FROM_EMAIL}